import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  entries: [
    'src/index',
    'src/content',
    'src/kit',
    'src/devtools',
    'src/i18n',
    'src/pro',
    'src/client/index',
    'src/client/composables/rpc',
    'src/client/composables/shiki',
  ],
  declaration: true,
  externals: [
    '@nuxt/schema',
    '@nuxt/kit',
    '@nuxt/devtools-kit',
    '@nuxt/devtools-kit/types',
    '@nuxt/devtools-kit/iframe-client',
    'nuxt',
    'nuxt/schema',
    'nuxt/app',
    'vue',
    'shiki',
    'shiki/core',
    'shiki/engine/javascript',
    '@shikijs/themes/vitesse-light',
    '@shikijs/themes/vitesse-dark',
    '@shikijs/langs/xml',
    '@shikijs/langs/json',
    '@shikijs/langs/js',
    '@vueuse/core',
    'nuxt-site-config',
    'nuxt-site-config/kit',
    '@nuxtjs/i18n',
    '@clack/prompts',
    'zod',
    '@nuxt/content',
  ],
})
