import { defineBuildConfig } from 'unbuild'

export default defineBuildConfig({
  declaration: true,
  failOnWarn: false,
  entries: [
    { input: 'src/content', name: 'content' },
    { input: 'src/kit', name: 'kit' },
    { input: 'src/devtools', name: 'devtools' },
    { input: 'src/i18n', name: 'i18n' },
    { input: 'src/pro', name: 'pro' },
    { input: 'src/utils', name: 'utils' },
  ],
  externals: [
    /^nitropack/,
    /^@nuxtjs\/i18n/,
    /^@nuxt\/content/,
    /^@nuxt\/schema/,
    /^@nuxt\/devtools-kit/,
    /^@nuxt\/kit/,
    /^@clack\/prompts/,
    /^nuxt/,
    /^nuxt-site-config/,
    /^vue/,
    /^zod/,
    /^node:/,
    /^consola/,
    /^defu/,
    /^ofetch/,
    /^pathe/,
    /^radix3/,
    /^sirv/,
    /^pkg-types/,
    /^std-env/,
    /^ufo/,
  ],
})
