packages:
  - docs
  - playground
  - packages/*
  - packages/*/playground
  - '!**/.data/**'
catalog:
  '@antfu/eslint-config': ^7.7.3
  '@arethetypeswrong/cli': ^0.18.2
  '@clack/prompts': ^1.1.0
  '@nuxt/content': ^3.12.0
  '@nuxt/devtools-kit': 4.0.0-alpha.3
  '@nuxt/fonts': ^0.14.0
  '@nuxt/kit': ^4.4.2
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.4.2
  '@nuxt/test-utils': ^4.0.0
  '@nuxt/ui': ^4.6.0
  '@nuxtjs/i18n': ^10.2.4
  '@nuxtjs/robots': ^6.0.1
  '@nuxtjs/sitemap': ^8.0.1
  '@resvg/resvg-js': ^2.6.2
  '@shikijs/langs': ^4.0.2
  '@shikijs/themes': ^4.0.2
  '@types/jest-image-snapshot': ^6.4.1
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^14.2.1
  '@vueuse/nuxt': ^14.2.1
  birpc: ^4.0.0
  bumpp: ^11.0.1
  consola: ^3.4.2
  defu: ^6.1.4
  eslint: ^10.1.0
  eslint-plugin-harlanzw: ^0.11.0
  execa: ^9.6.1
  happy-dom: ^20.8.8
  jest-image-snapshot: ^6.5.2
  lint-staged: ^16.4.0
  nitropack: ^2.13.2
  nuxt: ^4.4.2
  nuxt-link-checker: ^5.0.1
  nuxt-og-image: ^6.2.0
  nuxt-schema-org: ^6.0.0
  nuxt-seo-utils: ^8.0.1
  nuxt-site-config: ^4.0.1
  ofetch: ^1.5.1
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  radix3: ^1.1.2
  satori: ^0.26.0
  shiki: ^4.0.2
  simple-git-hooks: ^2.13.1
  sirv: ^3.0.2
  std-env: ^4.0.0
  typescript: ^6.0.2
  ufo: ^1.6.3
  unbuild: ^3.6.1
  vitest: ^4.1.1
  vue: ^3.5.30
  vue-tsc: ^3.2.6

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - maplibre-gl
  - sharp
  - vue-demi
  - workerd

onlyBuiltDependencies:
  - better-sqlite3
overrides:
  rollup-plugin-dts: ^6.4.1
  semver: ^7.7.4
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 262800
