catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - playground
  - '!**/.data/**'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - maplibre-gl
  - sharp
  - vue-demi
  - workerd
