import config from 'nuxt-seo-kit/config'
import { defineEventHandler, setHeader } from 'h3'

export default defineEventHandler(async (event) => {
  setHeader(event, 'Content-Type', 'text/plain')
  const debug = process.dev ? (`# Dev Mode: Generated by nuxt-seo-kit for ${config.hostname}. Indexing is ${config.indexable ? 'allowed' : 'disallowed'}\n`) : ''
  return `${debug}User-agent: *\nDisallow: ${config.indexable ? `\nSitemap: ${config.hostname}/sitemap.xml` : '/'}`
})
