import type { Nuxt } from '@nuxt/schema'
import type { Nitro } from 'nitropack'
import type { NitroConfig } from 'nitropack/types'
import type { NuxtModule, NuxtPage } from 'nuxt/schema'
import { addTemplate, createResolver, hasNuxtModule, hasNuxtModuleCompatibility, loadNuxtModuleInstance, tryUseNuxt, useNuxt } from '@nuxt/kit'
import { relative } from 'pathe'
import { env, provider } from 'std-env'

const autodetectableProviders: Record<string, string> = {
  azure_static: 'azure',
  cloudflare_pages: 'cloudflare-pages',
  netlify: 'netlify',
  stormkit: 'stormkit',
  vercel: 'vercel',
  cleavr: 'cleavr',
  stackblitz: 'stackblitz',
}

const autodetectableStaticProviders: Record<string, string> = {
  netlify: 'netlify-static',
  vercel: 'vercel-static',
}

export function detectTarget(options: { static?: boolean } = {}): string | undefined {
  return options?.static ? autodetectableStaticProviders[provider] : autodetectableProviders[provider]
}

export function resolveNitroPreset(nitroConfig?: NitroConfig): string {
  nitroConfig = nitroConfig || tryUseNuxt()?.options?.nitro
  if (provider === 'stackblitz' || provider === 'codesandbox')
    return provider
  let preset
  if (nitroConfig && nitroConfig?.preset)
    preset = nitroConfig.preset
  if (!preset)
    preset = env.NITRO_PRESET || env.SERVER_PRESET || detectTarget() || 'node-server'
  return preset.replace('_', '-')
}

/**
 * Get the user provided options for a Nuxt module.
 *
 * These options may not be the resolved options that the module actually uses.
 */
export async function getNuxtModuleOptions(module: string | NuxtModule, nuxt: Nuxt = useNuxt()): Promise<Record<string, any>> {
  const moduleMeta = (typeof module === 'string' ? { name: module } : await module.getMeta?.()) || {}
  const { nuxtModule } = (await loadNuxtModuleInstance(module, nuxt))

  let moduleEntry: [string | NuxtModule, Record<string, any>] | undefined
  for (const m of nuxt.options.modules) {
    if (Array.isArray(m) && m.length >= 2) {
      const _module = m[0]
      const _moduleEntryName = typeof _module === 'string'
        ? _module
        : (await (_module as any as NuxtModule).getMeta?.())?.name || ''
      if (_moduleEntryName === moduleMeta.name)
        moduleEntry = m as [string | NuxtModule, Record<string, any>]
    }
  }

  let inlineOptions = {}
  if (moduleEntry)
    inlineOptions = moduleEntry[1]
  if (nuxtModule.getOptions)
    return nuxtModule.getOptions(inlineOptions, nuxt)
  return inlineOptions
}

export function isNuxtGenerate(nuxt: Nuxt = useNuxt()): boolean {
  return nuxt.options.nitro.static || (nuxt.options as any)._generate || [
    'static',
    'github-pages',
  ].includes(resolveNitroPreset(nuxt.options.nitro))
}

/**
 * Generate TypeScript type augmentations for a Nuxt module.
 */
export function extendTypes(module: string, template: (options: { typesPath: string }) => string | Promise<string>): void {
  const nuxt = useNuxt()
  const { resolve } = createResolver(import.meta.url)
  addTemplate({
    filename: `module/${module}.d.ts`,
    getContents: async () => {
      const typesPath = relative(resolve(nuxt!.options.rootDir, nuxt!.options.buildDir, 'module'), resolve('runtime/types'))
      const s = await template({ typesPath })
      return `// Generated by ${module}\n${s}\nexport {}\n`
    },
  })

  nuxt.hooks.hook('prepare:types', ({ references }) => {
    references.push({ path: resolve(nuxt.options.buildDir, `module/${module}.d.ts`) })
  })
}

/**
 * Create a promise that resolves when Nuxt pages are resolved.
 */
export function createPagesPromise(nuxt: Nuxt = useNuxt()): Promise<NuxtPage[]> {
  return new Promise<NuxtPage[]>((resolve) => {
    nuxt.hooks.hook('modules:done', () => {
      if ((typeof nuxt.options.pages === 'boolean' && nuxt.options.pages === false) || (typeof nuxt.options.pages === 'object' && !nuxt.options.pages.enabled)) {
        return resolve([])
      }
      nuxt.hook('pages:resolved', pages => resolve(pages))
    })
  })
}

/**
 * Create a promise that resolves when Nitro is initialized.
 */
export function createNitroPromise(nuxt: Nuxt = useNuxt()): Promise<Nitro> {
  return new Promise<Nitro>((resolve) => {
    nuxt.hooks.hook('nitro:init', nitro => resolve(nitro))
  })
}

export interface NuxtContentVersion {
  version: 2 | 3
}

/**
 * Detect which version of @nuxt/content is installed.
 *
 * Returns `false` when @nuxt/content is not installed or the version is unrecognised.
 */
export async function resolveNuxtContentVersion(): Promise<false | NuxtContentVersion> {
  if (!hasNuxtModule('@nuxt/content'))
    return false
  if (await hasNuxtModuleCompatibility('@nuxt/content', '^3'))
    return { version: 3 }
  if (await hasNuxtModuleCompatibility('@nuxt/content', '^2'))
    return { version: 2 }
  return false
}
