import type { Nuxt } from '@nuxt/schema'
import type { Nitro } from 'nitropack'
import type { NitroConfig } from 'nitropack/types'
import type { NuxtModule, NuxtPage } from 'nuxt/schema'
import { addTemplate, createResolver, hasNuxtModule, hasNuxtModuleCompatibility, loadNuxtModuleInstance, tryUseNuxt, useNuxt } from '@nuxt/kit'
import { relative } from 'pathe'
import { readPackageJSON, resolvePackageJSON } from 'pkg-types'
import { env, provider } from 'std-env'

export interface NuxtSeoModuleDetection {
  name: string
  version?: string
  entryPath?: string
  features?: Record<string, boolean | string | number>
}

const NUXT_SEO_MODULES = new Set([
  '@nuxtjs/robots',
  '@nuxtjs/sitemap',
  'nuxt-og-image',
  'nuxt-schema-org',
  'nuxt-seo-utils',
  'nuxt-link-checker',
  'nuxt-site-config',
  'nuxt-skew-protection',
  'nuxt-ai-ready',
])

/**
 * Detect all installed Nuxt SEO modules from `nuxt.options._installedModules`.
 * No self-registration needed; modules are discovered automatically.
 */
export function detectNuxtSeoModules(nuxt: Nuxt = useNuxt()): NuxtSeoModuleDetection[] {
  return nuxt.options._installedModules
    .filter(m => m.meta?.name && NUXT_SEO_MODULES.has(m.meta.name))
    .map(m => ({
      name: m.meta.name!,
      version: m.meta.version,
      entryPath: m.entryPath,
    }))
}

const autodetectableProviders: Record<string, string> = {
  azure_static: 'azure',
  cloudflare_pages: 'cloudflare-pages',
  netlify: 'netlify',
  stormkit: 'stormkit',
  vercel: 'vercel',
  cleavr: 'cleavr',
  stackblitz: 'stackblitz',
}

const autodetectableStaticProviders: Record<string, string> = {
  netlify: 'netlify-static',
  vercel: 'vercel-static',
}

export function detectTarget(options: { static?: boolean } = {}): string | undefined {
  return options?.static ? autodetectableStaticProviders[provider] : autodetectableProviders[provider]
}

export function resolveNitroPreset(nitroConfig?: NitroConfig): string {
  nitroConfig = nitroConfig || (tryUseNuxt()?.options as any)?.nitro
  if (provider === 'stackblitz' || provider === 'codesandbox')
    return provider
  let preset
  if (nitroConfig && nitroConfig?.preset)
    preset = nitroConfig.preset
  if (!preset)
    preset = env.NITRO_PRESET || env.SERVER_PRESET || detectTarget() || 'node-server'
  return preset.replaceAll('_', '-')
}

/**
 * Get the user provided options for a Nuxt module.
 *
 * These options may not be the resolved options that the module actually uses.
 */
export async function getNuxtModuleOptions(module: string | NuxtModule, nuxt: Nuxt = useNuxt()): Promise<Record<string, any>> {
  const moduleMeta = (typeof module === 'string' ? { name: module } : await module.getMeta?.()) || {}
  const { nuxtModule } = (await loadNuxtModuleInstance(module, nuxt))

  let moduleEntry: [string | NuxtModule, Record<string, any>] | undefined
  for (const m of nuxt.options.modules) {
    if (Array.isArray(m) && m.length >= 2) {
      const _module = m[0]
      const _moduleEntryName = typeof _module === 'string'
        ? _module
        : (await (_module as any as NuxtModule).getMeta?.())?.name || ''
      if (_moduleEntryName === moduleMeta.name)
        moduleEntry = m as [string | NuxtModule, Record<string, any>]
    }
  }

  let inlineOptions = {}
  if (moduleEntry)
    inlineOptions = moduleEntry[1]
  if (nuxtModule.getOptions)
    return nuxtModule.getOptions(inlineOptions, nuxt)
  return inlineOptions
}

export function isNuxtGenerate(nuxt: Nuxt = useNuxt()): boolean {
  const nitroOptions = (nuxt.options as any).nitro
  return nitroOptions?.static || (nuxt.options as any)._generate || [
    'static',
    'github-pages',
  ].includes(resolveNitroPreset(nitroOptions))
}

/**
 * Generate TypeScript type augmentations for a Nuxt module.
 */
export function extendTypes(module: string, template: (options: { typesPath: string }) => string | Promise<string>): void {
  const nuxt = useNuxt()
  const { resolve } = createResolver(import.meta.url)
  addTemplate({
    filename: `module/${module}.d.ts`,
    getContents: async () => {
      const typesPath = relative(resolve(nuxt!.options.rootDir, nuxt!.options.buildDir, 'module'), resolve('runtime/types'))
      const s = await template({ typesPath })
      return `// Generated by ${module}\n${s}\nexport {}\n`
    },
  })

  nuxt.hooks.hook('prepare:types', ({ references }) => {
    references.push({ path: resolve(nuxt.options.buildDir, `module/${module}.d.ts`) })
  })
}

/**
 * Create a promise that resolves when Nuxt pages are resolved.
 */
export function createPagesPromise(nuxt: Nuxt = useNuxt()): Promise<NuxtPage[]> {
  return new Promise<NuxtPage[]>((resolve) => {
    nuxt.hooks.hook('modules:done', () => {
      if ((typeof nuxt.options.pages === 'boolean' && nuxt.options.pages === false) || (typeof nuxt.options.pages === 'object' && !nuxt.options.pages.enabled)) {
        return resolve([])
      }
      nuxt.hook('pages:resolved', pages => resolve(pages))
    })
  })
}

/**
 * Create a promise that resolves when Nitro is initialized.
 */
export function createNitroPromise(nuxt: Nuxt = useNuxt()): Promise<Nitro> {
  return new Promise<Nitro>((resolve) => {
    nuxt.hooks.hook('nitro:init' as any, (nitro: Nitro) => resolve(nitro))
  })
}

export interface NuxtContentVersion {
  version: 2 | 3
}

/**
 * Detect which version of @nuxt/content is installed.
 *
 * Returns `false` when @nuxt/content is not installed or the version is unrecognised.
 */
export async function resolveNuxtContentVersion(): Promise<false | NuxtContentVersion> {
  if (!hasNuxtModule('@nuxt/content'))
    return false
  if (await hasNuxtModuleCompatibility('@nuxt/content', '^3'))
    return { version: 3 }
  if (await hasNuxtModuleCompatibility('@nuxt/content', '^2'))
    return { version: 2 }
  return false
}

/**
 * Read the major version of a non-module package as resolved from `rootDir`.
 *
 * Unlike `hasNuxtModuleCompatibility`, this works for plain libraries (e.g.
 * `unhead`, `@unhead/vue`) that aren't registered as Nuxt modules. Returns
 * `undefined` when the package can't be resolved or has no parseable version.
 */
export async function resolvePackageMajor(id: string, rootDir: string): Promise<number | undefined> {
  const url = rootDir.endsWith('/') ? rootDir : `${rootDir}/`
  const version = await readPackageJSON(id, { url }).then(pkg => pkg.version).catch(() => {
    // an unresolvable package is an expected miss (it just isn't installed under
    // this id); the caller decides on a fallback.
    return undefined
  })
  const major = version ? Number.parseInt(version, 10) : Number.NaN
  return Number.isFinite(major) ? major : undefined
}

export type UnheadMajor = 2 | 3

/**
 * Resolve the major of the unhead the host app renders with.
 *
 * `@unhead/vue` is what the head-stack packages peer-depend on, so it's the
 * primary signal; falls back to the core `unhead` package, then to `3` (the
 * current default major) when neither resolves.
 *
 * Used to keep head-stack dependencies on a compatible major. For example,
 * `@unhead/schema-org` v3 attaches an object `_resolver` to every graph node
 * that unhead v2's `walkResolver` invokes as a thunk, crashing render; a module
 * that ships both majors can use this to alias to the matching one.
 */
export async function resolveHostUnheadMajor(rootDir: string): Promise<UnheadMajor> {
  const rootUrl = rootDir.endsWith('/') ? rootDir : `${rootDir}/`
  // Search roots for the host's unhead. Under pnpm's strict (non-hoisted) layout
  // `@unhead/vue`/`unhead` are transitive deps of `nuxt` and are NOT resolvable
  // from the project root, so detection would always miss and fall back to the
  // default major. Also search from `nuxt`'s install location, where the host's
  // unhead is always reachable.
  const searchUrls = [rootUrl]
  const nuxtJson = await resolvePackageJSON('nuxt', { url: rootUrl }).catch(() => {
    // a missing `nuxt` is an expected miss (e.g. a non-standard layout); we just
    // keep searching from the project root only.
    return undefined
  })
  if (nuxtJson)
    searchUrls.push(nuxtJson.replace(/[^/\\]+$/, ''))
  // `@unhead/vue` is what the head-stack packages peer-depend on; fall back to the
  // core `unhead` package when it isn't directly resolvable.
  for (const id of ['@unhead/vue', 'unhead']) {
    for (const url of searchUrls) {
      const major = await resolvePackageMajor(id, url)
      if (major === 2)
        return 2
      if (major !== undefined && major >= 3)
        return 3
    }
  }
  return 3
}
