name: Package Size Comment

on:
  workflow_run:
    workflows:
      - Package Size Analysis
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_repository.id }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

permissions: {}

jobs:
  comment:
    if: >-
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      actions: read
      pull-requests: write
    uses: harlan-zw/nuxt-seo/.github/workflows/reusable-package-size-comment.yml@main
