name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: harlan-zw/nuxt-seo/.github/workflows/reusable-ci.yml@main
