name: Nightly

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '!**'

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    uses: ./.github/workflows/reusable-nightly.yml
    with:
      runner: ubuntu-latest
      publish-packages: ./packages/nuxt-seo ./packages/shared
