name: Nightly

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '!**'

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true
          install: false

      - run: pnpm install --frozen-lockfile --trust-lockfile
      - run: pnpm dev:prepare

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm dlx pkg-pr-new publish --pnpm ./packages/nuxt-seo ./packages/shared
