name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/reusable-release.yml
    with:
      monorepo: true
      pre-build-command: pnpm dev:prepare
