name: Reusable Nightly

on:
  workflow_call:
    inputs:
      runner:
        description: Runner to use
        type: string
        default: ubuntu-latest
      node-version:
        description: Node.js version
        type: string
        default: lts
      pre-build-command:
        description: Command to run before build
        type: string
        default: ''
      prepare-command:
        description: Dev prepare command
        type: string
        default: 'pnpm dev:prepare'
      publish-packages:
        description: Space-separated list of package paths to publish (leave empty to
          publish all)
        type: string
        default: ''

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          runtime: node@${{ inputs.node-version }}
          cache: true
          install: false

      - run: pnpm install --frozen-lockfile --trust-lockfile
      - run: ${{ inputs.prepare-command }}

      - if: ${{ inputs.pre-build-command != '' }}
        run: ${{ inputs.pre-build-command }}

      - run: pnpm build

      - name: Publish
        run: pnpm dlx pkg-pr-new publish --pnpm ${{ inputs.publish-packages }}
