name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      playwright: false
      test-command: pnpm test:run
